'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Entity.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;html&gt;
        '''&lt;head&gt;
        '''    &lt;title&gt;Contacts&lt;/title&gt;
        '''    &lt;style&gt;
        '''        h1, p {
        '''            font-family: Segoe UI SemiLight, Helvetica, Sans-Serif;
        '''            font-weight: normal;
        '''            margin-top: 0;
        '''        }
        '''
        '''        h1 {
        '''            color: #494546;
        '''        }
        '''
        '''        p {
        '''            color: #393536;
        '''        }
        '''
        '''        div {
        '''            text-align: left;
        '''            border: 2px solid #828E8C;
        '''            width: 660px;
        '''            height: 230px;
        '''            margin: -134px 0 0 -330px;
        '''  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property contacts() As String
            Get
                Return ResourceManager.GetString("contacts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;html&gt;
        '''&lt;head&gt;
        '''    &lt;title&gt;The Code Project Open License (CPOL)&lt;/title&gt;
        '''    &lt;style&gt;
        '''        h1, h2, h3, p, ol li, ul li {
        '''            font-family: Segoe UI SemiLight, Helvetica, Sans-Serif;
        '''            font-weight: normal;
        '''            margin-top: 0;
        '''        }
        '''
        '''        a {
        '''            font-family: Segoe UI SemiLight, Helvetica, Sans-Serif;
        '''            font-weight: normal;
        '''            color: #D8765C;
        '''            text-decoration: none;
        '''        }
        '''
        '''            a:hover {
        '''                text-decor [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CPOL() As String
            Get
                Return ResourceManager.GetString("CPOL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to We wish to express our thanks to the following personnel for their invaluable contributions to this project:
        '''
        '''-General-
        '''
        '''Lead Programmer, Designer, and Tester
        '''Alex Yu (alexyu99126@gmail.com) of U-Hill Secondary
        '''
        '''Theatre Department
        '''Miss K. Penney
        '''
        '''-Source Code-
        '''
        '''Image Transition Effect
        '''Author: Anibal Svarcas
        '''Source Code from: http://www.elguille.info/colabora/puntoNET/anibal_EfectosTrans.htm (modified)
        '''License: None
        '''
        '''Enttec DMX to USB Driver for .Net
        '''Author: hippy
        '''Email: rowanmac@optusnet. [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property credits() As String
            Get
                Return ResourceManager.GetString("credits", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Document() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Document", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EditBtn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EditBtn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property en() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("en", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Folder() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Folder", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Headphones() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Headphones", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ModifyBtn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ModifyBtn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;html&gt;
        '''&lt;head&gt;
        '''    &lt;title&gt;The Microsoft Public License (MS-PL)&lt;/title&gt;
        '''    &lt;style&gt;
        '''        h1, h2, h3, p{
        '''            font-family: Segoe UI SemiLight, Helvetica, Sans-Serif;
        '''            font-weight: normal;
        '''            margin-top: 0;
        '''           }
        '''        a {
        '''            font-family: Segoe UI SemiLight, Helvetica, Sans-Serif;
        '''            font-weight: normal;
        '''            color: #D8765C;
        '''            text-decoration: none;
        '''        }
        '''            a:hover {
        '''                text-decoration: none;
        '''   [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property MSPL() As String
            Get
                Return ResourceManager.GetString("MSPL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property photo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("photo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SettingsIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SettingsIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property U_Hill_Logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("U_Hill_Logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Video() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Video", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property YouTube() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("YouTube", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
